# Generated by Django 5.0.6 on 2024-05-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='malumot',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
